# -*- coding: utf-8 -*-
"""จองสนาม.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZHzRRqqaR8YN2lXaEQomrM7No4a_ZwCM
"""

class SportBooking:

    def __init__(self):
        self.bookings = []

        self.fields = {
            "1": "สนามฟุตบอล 1",
            "2": "สนามฟุตบอล 2",
            "3": "สนามแบดมินตัน 1",
            "4": "สนามแบดมินตัน 2",
            "5": "สนามแบดมินตัน 3"
        }
        self.price = {
            "สนามฟุตบอล 1": 500,
            "สนามฟุตบอล 2": 500,
            "สนามแบดมินตัน 1": 200,
            "สนามแบดมินตัน 2": 200,
            "สนามแบดมินตัน 3": 200
        }

        self.times = [
            "08:00-09:00",
            "09:00-10:00",
            "10:00-11:00",
            "11:00-12:00",
            "13:00-14:00",
            "14:00-15:00",
            "15:00-16:00",
            "16:00-17:00"
        ]

    def show_fields(self):
        print("\n===== สนามกีฬา =====")
        for k, v in self.fields.items():
            print(k, ".", v)

    def booking(self):

        name = input("ชื่อผู้จอง : ")

        self.show_fields()

        choose = input("เลือกสนาม : ")

        if choose not in self.fields:
            print("ไม่มีสนามนี้")
            return

        field = self.fields[choose]

        date = input("วันที่ (dd/mm/yyyy): ")

        print("\nช่วงเวลา")

        for i in range(len(self.times)):
            print(i+1, ".", self.times[i])

        start = int(input("เลือกเวลาเริ่ม : ")) - 1

        hour = int(input("จำนวนชั่วโมง : "))

        if start + hour > len(self.times):
            print("❌ จองเกินเวลาปิดสนาม")
            return

        # ตรวจสอบเวลาซ้ำ
        for i in range(start, start+hour):

            for b in self.bookings:

                if b["สนาม"] == field and \
                   b["วันที่"] == date and \
                   b["เวลา"] == self.times[i]:

                    print("❌ มีผู้จองช่วง", self.times[i], "แล้ว")
                    return

        # -----------------------
        # คำนวณราคา
        # -----------------------

        total = self.price[field] * hour

        print("\n========== สรุปรายการ ==========")
        print("ชื่อ :", name)
        print("สนาม :", field)
        print("วันที่ :", date)
        print("จำนวนชั่วโมง :", hour)
        print("ยอดชำระ :", total, "บาท")

        # -----------------------
        # เลือกวิธีชำระเงิน
        # -----------------------

        print("\nวิธีชำระเงิน")
        print("1. พร้อมเพย์")

        pay = input("เลือก : ")

        if pay == "1":

          print("\n===== พร้อมเพย์ =====")
          print("ยอดชำระ :", total, "บาท")
          input("กด Enter หลังจากชำระเงิน...")

          print("✅ ชำระเงินสำเร็จ")

        else:
          print("เลือกไม่ถูกต้อง")
          return

# -----------------------
# บันทึกข้อมูล
# -----------------------

        for i in range(start, start+hour):

          self.bookings.append({
          "ชื่อ": name,
          "สนาม": field,
          "วันที่": date,
          "เวลา": self.times[i]
      })

        print("\n🎉 จองสนามเรียบร้อย")
    def history(self):

        name = input("กรอกชื่อสมาชิก : ")

        print("\n===== ประวัติการจอง =====")

        found = False

        for b in self.bookings:

            if b["ชื่อ"] == name:

                print("--------------------")
                print("สนาม :", b["สนาม"])
                print("วันที่ :", b["วันที่"])
                print("เวลา :", b["เวลา"])

                found = True

        if not found:
            print("ไม่พบข้อมูล")

    def menu(self):

        while True:

            print("""
======== ระบบจองสนามกีฬา ========

1. จองสนาม
2. ประวัติการจอง
3. ออก
""")

            choose = input("เลือกเมนู : ")

            if choose == "1":
                self.booking()

            elif choose == "2":
                self.history()

            elif choose == "3":
                print("ขอบคุณที่ใช้บริการ")
                break

            else:
                print("เลือกใหม่")


# เริ่มโปรแกรม
app = SportBooking()
app.menu()